name: Test Sequential jobs
on: 
  - push
  - workflow_dispatch
jobs: 
  first-event:
    runs-on: ubuntu-latest
    steps:
      - name: create 1st dummy event
        run: python -c "print('One-liner inline Python')"

  subsequent-event:
    needs: first-event
    runs-on: ubuntu-latest
    steps:
      - name: complete program
        id: notify 
        run: echo "Program execution Completed!"

  inspect-context-objects:
    runs-on: ubuntu-latest
    steps: 
      - name: github context inspection
        run: echo "${{ github.repository }}"
      - name: check step details
        run: echo "${{ steps.notify.outputs }}"
     